### ISSUE TITLE
Add Linux CI support

### ISSUE THREAD

**Issue by lijunle** [atom/ci#2]
Any plan for these?

**Comment by vinicarlos56** [comment]
Hi @kevinsawicki, I just have tested one Linux version for my package and I managed to get it working on travis, I made some changes on the [build-package.sh](https://github.com/vinicarlos56/ci/blob/master/build-package.sh) file to adapt and tweak some issues I found.

Check the latest [build](https://travis-ci.org/vinicarlos56/php-composer-autocompletion) apparently everything is ok.

Let me know if you want to add the changes to the main repository.

Cheers

**Comment by levlaz** [comment]
Hello! 

I updated instructions https://github.com/atom/ci/pull/21 on how to use CircleCI to test atom packages. By default CircleCI uses an Ubuntu Linux container.

**Comment by levlaz** [comment]
@kevinsawicki I got the same method to work as I used on CircleCI on Travis, for the PR how should I handle having two `.travis.yml` files in this repo?

We can either have .travis_linux.yml (and tell people to rename), or perhaps just have a branch?

**Comment by kevinsawicki** [comment]
> We can either have .travis_linux.yml (and tell people to rename), or perhaps just have a branch?

How about `linux.travis.yml`?

**Comment by levlaz** [comment]
Hi Kevin, 

Works for me! I'll send a PR :) 

Best, 
Lev

**Comment by joefitzgerald** [comment]
See #22.
