### ISSUE TITLE
Travis script throws an error if package doesn't contain a spec folder

### ISSUE THREAD

**Issue by mnquintana** [atom/ci#30]
Refs https://travis-ci.org/atom/language-text/builds/99831825

If a package doesn't have a spec folder (like many language packages still), then it seems like the Travis script throws an error. Although we definitely should encourage packages to have specs, this strikes me as a bit of a deceptive blow up – I think we should either throw a more helpful error (e.g. ~"plz add specs") or not blow up in the absence of specs.

**Comment by lee-dohm** [comment]
I'd recommend erring on the side of adding a more helpful message.
