### ISSUE TITLE
Move back to bundled Node.js?

### ISSUE THREAD

**Issue by Arcanemagus** [atom/ci#52]
Now that Atom v1.10.0 is on stable, should the CI scripts default back to using the bundled Node.js for everything? Keeping the option to override if necessary, of course.

**Comment by joefitzgerald** [comment]
So this pertains to: https://github.com/atom/ci/blob/519080ae0e7a073be40c6a868e6c7e5dc373ebbd/.travis.yml#L5 ?

**Comment by Arcanemagus** [comment]
Correct, changing the default, recommended, option back to the old behavior of using the bundled Node.js, since it is now new enough that it shouldn't be causing issues installing things.

**Comment by thomasjo** [comment]
I'm voting 👍 on moving back to bundled Node, but mostly just because it means we can 🔥 that variable from the config. Although I guess in some sense it might be more "surprising" that linting isn't done using whatever version of Node the user chooses to install in their CI environment... 💭

**Comment by Arcanemagus** [comment]
My vote is for moving back to the bundled Node.js... but leaving the variable there (just `true`), and commenting out the steps to install the system Node.js.

I guess I would be fine with nuking the Node installation entirely, but as this repo is meant for people that don't know how to set up CI already I'd say it should be left in.

**Comment by joefitzgerald** [comment]
We could remove the variable from .travis.yml and the other CI scripts but leave it in the build-package scripts; if it is defaulted to true that does not preclude someone setting it to false. I agree that we should clean this up, and remove extraneous steps / configuration.

**Comment by joefitzgerald** [comment]
I think we have consensus that we should move back to the bundled node by default. This could mean we could remove the variable from the CI scripts, and ensure the default is set correctly in `build-package.sh` and `build-package.ps1`.

**Comment by Arcanemagus** [comment]
I think the variable should still be shown in the scripts, in the same manner as `APM_TEST_PACKAGES` is currently. Without it there a package author would have to take the trouble to read through the scripts or README to realize it was there.

**Comment by joefitzgerald** [comment]
> I think the variable should still be shown in the scripts, in the same manner as APM_TEST_PACKAGES is currently.

OK, fair enough.

**Comment by Arcanemagus** [comment]
I can put a PR together for this, but would like to know whether to leave the installation of Node.js 6 in the scripts, comment it out, or remove it entirely and let users figure it out on their own if it's necessary in the future.

As it seems the goal of this is "as simple as possible of a configuration to get going", I guess I would be for removing it entirely.
