### ISSUE TITLE
Stop using `appveyor` command

### ISSUE THREAD

**Issue by thomasjo** [atom/ci#53]
The use of the [`appveyor` command](https://github.com/atom/ci/blob/519080ae0e7a073be40c6a868e6c7e5dc373ebbd/build-package.ps1#L29) in the PowerShell script is currently preventing the CI script from being executed in other environments.

There is no good reason for using that command, so we should replace it.

**Comment by Arcanemagus** [comment]
AppVeyor lists several alternatives here: https://www.appveyor.com/docs/how-to/download-file/

**Comment by joefitzgerald** [comment]
I reverted this in 3ff137ac414d8a904be02acc328cd3ecde67e617, per reasoning in #55.
