### ISSUE TITLE
Investigate AppVeyor failures

### ISSUE THREAD

**Issue by Arcanemagus** [atom/ci#55]
It looks like 02e826899a7db8d9c36b6f2dfef33f553c21344d might have broken downloads on AppVeyor: https://ci.appveyor.com/project/Arcanemagus/linter-stylelint/build/437/job/envtf2j641tli3l5

I'm checking if any other builds have failed while using the new method.

**Comment by Arcanemagus** [comment]
Looks like it can't be that change, as [this build](https://ci.appveyor.com/project/Arcanemagus/linter-stylelint/build/436/job/v5d7rlhlnp1wkq0j) is before it landed, and [this build](https://ci.appveyor.com/project/Arcanemagus/linter-eslint/build/473/job/ldfqwlt2r13ab2ls) used it just fine.

**Comment by joefitzgerald** [comment]
Yeah there's a reason I was using the Appveyor CLI. After extensive testing, it was by far the most reliable. Suggest we revert the change and then add logic that uses the appveyor CLI on appveyor and another technique when not on appveyor.

**Comment by Arcanemagus** [comment]
Also, turns out the _commit_ for https://ci.appveyor.com/project/Arcanemagus/linter-stylelint/build/436 was 2 days ago, the build was only 4 hours ago, so it was definitely running with this commit.

**Comment by Arcanemagus** [comment]
Looks like that fixed it: https://ci.appveyor.com/project/Arcanemagus/linter-stylelint/build/job/7muipja0rd6k2btx
