### ISSUE TITLE
Travis fails to install libsecret-1-dev

### ISSUE THREAD

**Issue by subesokun** [atom/ci#70]
With the latest build configuration for Travis CI from this repository my builds are failing with the following error:

```
E: Unable to locate package libsecret-1-dev
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install build-essential git libgnome-keyring-dev libsecret-1-dev fakeroot" failed and exited with 100 during .
Your build has been stopped.
```

https://travis-ci.org/subesokun/atom-tree-view-git-status/jobs/234570128

Some ideas how to solve this issue? Thanks a lot :)

**Comment by Arcanemagus** [comment]
Looks like your build ran [as `precise`](https://travis-ci.org/subesokun/atom-tree-view-git-status/jobs/234570128#L2) not the required `trusty`. The [recommended build config](https://github.com/atom/ci/blob/master/.travis.yml) was (somewhat) recently updated to use the `trusty` image as it is required on Atom v1.18.0 and above.

(_Technically_ you can make it work on older versions of Ubuntu, but it's apparently somewhat of a pain to get working right on Travis-CI.)

**Comment by Arcanemagus** [comment]
@subesokun As it looks like this issue was solved you should close this 😉.

Note that there have been [further changes](https://github.com/atom/ci/pull/73) required since this issue was opened, you should check the current state of the Travis CI configuration in `master`.

**Comment by subesokun** [comment]
@Arcanemagus Sorry, totally forgot to reply! Your last hint has solved my issue and thanks a lot for your support :)! I'll have a look on the new configuration.
