### ISSUE TITLE
New dependencies for Ubuntu

### ISSUE THREAD

**Issue by DavidLGoldberg** [atom/ci#72]
The following commit fixed some issues I was having with the current .travis.yml version in master.

Will others need this fix?  Should I make a PR? (I copied this portion from atom/atom's .travis.yml).

https://github.com/DavidLGoldberg/qolor/commit/41392c4847f1723116426e62a70b06fa5e563b1b

**Comment by 50Wliu** [comment]
Yeah, we would definitely take a PR if it's something wrong with the CI configuration.

**Comment by Arcanemagus** [comment]
@DavidLGoldberg are you sure it wasn't the addition of `dist: trusty` that fixed your builds? That has been required for beta builds since Atom v1.18, and now would be required for stable builds.

I have quite a few builds successfully completing without the addition of those packages you show.

**Comment by Arcanemagus** [comment]
Whoops, I take that back, turns out the build I pulled up to check was actually one of the few still running on the macOS VMs, this is definitely an issue on the beta builds. I'll put up a PR.
