### ISSUE TITLE
Install node with npm ci

### ISSUE THREAD

**Issue by jonyeezs** [atom/ci#84]
Since node 5.7, they have introduce `npm ci` which installs from package-lock instead of upgrading on semver.

This would maintain the CI's version and speed up build time.

**Comment by Arcanemagus** [comment]
Atom packages are installed using `apm`, not `npm`. The CI environment uses `apm` to install modules to match the environment that users will be using to install the package.

You can look through the [atom/apm](https://github.com/atom/apm) repository for further insights about getting the `npm` version it uses behind the scenes updated, as currently it doesn't actually understand `package-lock.json` files in the first place.

Thanks for taking the time to file an issue!
