### ISSUE TITLE
Dev channel builds failing on Travis CI

### ISSUE THREAD

**Issue by jasonrudolph** [atom/ci#93]
### Description 

When a package's build runs on Travis CI, and the build matrix includes the dev channel, Travis CI fails while installing Atom. 

For example, the [atom/ci README refers to atom/wrap-guide](https://github.com/atom/ci/tree/25b04066170a9c9c6888d43bb116396e69a73c34#travis-ci) as an example of how to atom/ci is intended to be used. But when Travis CI attempts to run CI for atom/wrap-guide, it fails while trying to install the Atom dev release:

```
dpkg-deb: error: archive 'atom-amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
```

We first [observed this issue in the Teletype nightly build](https://travis-ci.org/atom/teletype/jobs/551600740#L521), but it appears to affect any Atom package that attempts to run CI against the Atom dev channel release. For example, we can see the same failure in atom/wrap-guide's build: https://travis-ci.org/atom/wrap-guide/jobs/551945689#L509

**Comment by jasonrudolph** [comment]
At the moment, my best guess is that this issue is somehow related to the recent changes in https://github.com/atom/atom/pull/19597, in which the dev channel build of atom/atom is now served from Azure Pipelines instead of Travis CI. Teletype's nightly builds were fine prior to when https://github.com/atom/atom/pull/19597 was merged, and they started failing after https://github.com/atom/atom/pull/19597 was merged. This seems unlikely to be just a coincidence. 🤔 

<img width="996" alt="Screen Shot 2019-06-28 at 4 49 45 PM" src="https://user-images.githubusercontent.com/2988/60370596-04d22a00-99c5-11e9-9f1b-cc0440c72409.png">

**Comment by nathansobo** [comment]
My plan is to upgrade to Ubuntu 16 on all of our package builds.

**Comment by nathansobo** [comment]
Okay, I've audited all of our packages. Most of them don't build on Linux or are bundled. I upgraded the few that build on Linux to Xenial to avoid any issues on the next release, because that will cause artifacts from Azure Pipelines to be on the stable channel for the first time. We should be good to go.
